package com.airwallex.android.view.util

/**
 *
 * Rule:
 *  - State field is shown only for countries whose `fmt` in address.json contains `%S`.
 *  - If sub_keys exist for that country, render as a dropdown of those values.
 *  - Otherwise render as a free-text input (only SC at the time of porting).
 *  - For any other country, hide the state field entirely.
 */
@Suppress("LargeClass") // Hand-port of address.json — size is data, not complexity.
internal object AddressSpec {

    /** Countries whose `fmt` contains `%S` but have no sub_keys list — render state as free text. */
    private val STATE_FREETEXT_COUNTRIES: Set<String> = setOf(
        "SC",
    )

    /** Map of country code → list of (value, label) for the state dropdown. */
    private val STATE_LISTS: Map<String, List<Pair<String, String>>> = mapOf(
        "AE" to listOf(
            "أبو ظبي" to "أبو ظبي — Abu Dhabi",
            "إمارة الشارقةّ" to "الشارقة — Sharjah",
            "الفجيرة" to "الفجيرة — Fujairah",
            "ام القيوين" to "ام القيوين — Umm Al Quwain",
            "إمارة دبيّ" to "دبي — Dubai",
            "إمارة رأس الخيمة" to "رأس الخيمة — Ras al Khaimah",
            "عجمان" to "عجمان — Ajman",
        ),
        "AM" to listOf(
            "Արագածոտն" to "Արագածոտն — Aragatsotn",
            "Արարատ" to "Արարատ — Ararat",
            "Արմավիր" to "Արմավիր — Armavir",
            "Գեղարքունիք" to "Գեղարքունիք — Gegharkunik",
            "Երևան" to "Երևան — Yerevan",
            "Լոռի" to "Լոռի — Lori",
            "Կոտայք" to "Կոտայք — Kotayk",
            "Շիրակ" to "Շիրակ — Shirak",
            "Սյունիք" to "Սյունիք — Syunik",
            "Վայոց ձոր" to "Վայոց ձոր — Vayots Dzor",
            "Տավուշ" to "Տավուշ — Tavush",
        ),
        "AR" to listOf(
            "Buenos Aires" to "Buenos Aires",
            "Catamarca" to "Catamarca",
            "Chaco" to "Chaco",
            "Chubut" to "Chubut",
            "Ciudad Autónoma de Buenos Aires" to "Ciudad Autónoma de Buenos Aires",
            "Córdoba" to "Córdoba",
            "Corrientes" to "Corrientes",
            "Entre Ríos" to "Entre Ríos",
            "Formosa" to "Formosa",
            "Jujuy" to "Jujuy",
            "La Pampa" to "La Pampa",
            "La Rioja" to "La Rioja",
            "Mendoza" to "Mendoza",
            "Misiones" to "Misiones",
            "Neuquén" to "Neuquén",
            "Río Negro" to "Río Negro",
            "Salta" to "Salta",
            "San Juan" to "San Juan",
            "San Luis" to "San Luis",
            "Santa Cruz" to "Santa Cruz",
            "Santa Fe" to "Santa Fe",
            "Santiago del Estero" to "Santiago del Estero",
            "Tierra del Fuego" to "Tierra del Fuego",
            "Tucumán" to "Tucumán",
        ),
        "AU" to listOf(
            "ACT" to "Australian Capital Territory",
            "NSW" to "New South Wales",
            "NT" to "Northern Territory",
            "QLD" to "Queensland",
            "SA" to "South Australia",
            "TAS" to "Tasmania",
            "VIC" to "Victoria",
            "WA" to "Western Australia",
        ),
        "BB" to listOf(
            "Christ Church" to "Christ Church",
            "Saint Andrew" to "Saint Andrew",
            "Saint George" to "Saint George",
            "Saint James" to "Saint James",
            "Saint John" to "Saint John",
            "Saint Joseph" to "Saint Joseph",
            "Saint Lucy" to "Saint Lucy",
            "Saint Michael" to "Saint Michael",
            "Saint Peter" to "Saint Peter",
            "Saint Philip" to "Saint Philip",
            "Saint Thomas" to "Saint Thomas",
        ),
        "BR" to listOf(
            "AC" to "Acre",
            "AL" to "Alagoas",
            "AP" to "Amapá",
            "AM" to "Amazonas",
            "BA" to "Bahia",
            "CE" to "Ceará",
            "DF" to "Distrito Federal",
            "ES" to "Espírito Santo",
            "GO" to "Goiás",
            "MA" to "Maranhão",
            "MT" to "Mato Grosso",
            "MS" to "Mato Grosso do Sul",
            "MG" to "Minas Gerais",
            "PA" to "Pará",
            "PB" to "Paraíba",
            "PR" to "Paraná",
            "PE" to "Pernambuco",
            "PI" to "Piauí",
            "RJ" to "Rio de Janeiro",
            "RN" to "Rio Grande do Norte",
            "RS" to "Rio Grande do Sul",
            "RO" to "Rondônia",
            "RR" to "Roraima",
            "SC" to "Santa Catarina",
            "SP" to "São Paulo",
            "SE" to "Sergipe",
            "TO" to "Tocantins",
        ),
        "BS" to listOf(
            "Abaco" to "Abaco Islands",
            "Acklins" to "Acklins",
            "Andros" to "Andros Island",
            "Berry Islands" to "Berry Islands",
            "Bimini" to "Bimini",
            "Cat Island" to "Cat Island",
            "Crooked Island" to "Crooked Island",
            "Eleuthera" to "Eleuthera",
            "Exuma" to "Exuma and Cays",
            "Grand Bahama" to "Grand Bahama",
            "Harbour Island" to "Harbour Island",
            "Inagua" to "Inagua",
            "Long Island" to "Long Island",
            "Mayaguana" to "Mayaguana",
            "N.P." to "New Providence",
            "Ragged Island" to "Ragged Island",
            "Rum Cay" to "Rum Cay",
            "San Salvador" to "San Salvador",
            "Spanish Wells" to "Spanish Wells",
        ),
        "CA" to listOf(
            "AB" to "Alberta",
            "BC" to "British Columbia",
            "MB" to "Manitoba",
            "NB" to "New Brunswick",
            "NL" to "Newfoundland and Labrador",
            "NT" to "Northwest Territories",
            "NS" to "Nova Scotia",
            "NU" to "Nunavut",
            "ON" to "Ontario",
            "PE" to "Prince Edward Island",
            "QC" to "Quebec",
            "SK" to "Saskatchewan",
            "YT" to "Yukon",
        ),
        "CL" to listOf(
            "Antofagasta" to "Antofagasta",
            "Araucanía" to "Araucanía",
            "Arica y Parinacota" to "Arica y Parinacota",
            "Atacama" to "Atacama",
            "Aysén" to "Aysén del General Carlos Ibáñez del Campo",
            "Biobío" to "Biobío",
            "Coquimbo" to "Coquimbo",
            "O'Higgins" to "Libertador General Bernardo O'Higgins",
            "Los Lagos" to "Los Lagos",
            "Los Ríos" to "Los Ríos",
            "Magallanes" to "Magallanes y de la Antártica Chilena",
            "Maule" to "Maule",
            "Región Metropolitana" to "Metropolitana de Santiago",
            "Ñuble" to "Ñuble",
            "Tarapacá" to "Tarapacá",
            "Valparaíso" to "Valparaíso",
        ),
        "CN" to listOf(
            "安徽省" to "安徽省 — Anhui Sheng",
            "澳门" to "澳门 — Macau",
            "北京市" to "北京市 — Beijing Shi",
            "重庆市" to "重庆市 — Chongqing Shi",
            "福建省" to "福建省 — Fujian Sheng",
            "甘肃省" to "甘肃省 — Gansu Sheng",
            "广东省" to "广东省 — Guangdong Sheng",
            "广西壮族自治区" to "广西 — Guangxi Zhuangzuzizhiqu",
            "贵州省" to "贵州省 — Guizhou Sheng",
            "海南省" to "海南省 — Hainan Sheng",
            "河北省" to "河北省 — Hebei Sheng",
            "河南省" to "河南省 — Henan Sheng",
            "黑龙江省" to "黑龙江省 — Heilongjiang Sheng",
            "湖北省" to "湖北省 — Hubei Sheng",
            "湖南省" to "湖南省 — Hunan Sheng",
            "吉林省" to "吉林省 — Jilin Sheng",
            "江苏省" to "江苏省 — Jiangsu Sheng",
            "江西省" to "江西省 — Jiangxi Sheng",
            "辽宁省" to "辽宁省 — Liaoning Sheng",
            "内蒙古自治区" to "内蒙古 — Neimenggu Zizhiqu",
            "宁夏回族自治区" to "宁夏 — Ningxia Huizuzizhiqu",
            "青海省" to "青海省 — Qinghai Sheng",
            "山东省" to "山东省 — Shandong Sheng",
            "山西省" to "山西省 — Shanxi Sheng",
            "陕西省" to "陕西省 — Shaanxi Sheng",
            "上海市" to "上海市 — Shanghai Shi",
            "四川省" to "四川省 — Sichuan Sheng",
            "台湾" to "台湾 — Taiwan",
            "天津市" to "天津市 — Tianjin Shi",
            "西藏自治区" to "西藏 — Xizang Zizhiqu",
            "香港" to "香港 — Hong Kong",
            "新疆维吾尔自治区" to "新疆 — Xinjiang Weiwuerzizhiqu",
            "云南省" to "云南省 — Yunnan Sheng",
            "浙江省" to "浙江省 — Zhejiang Sheng",
        ),
        "CO" to listOf(
            "DC" to "Distrito Capital de Bogotá",
            "AMA" to "Amazonas",
            "ANT" to "Antioquia",
            "ARA" to "Arauca",
            "ATL" to "Atlántico",
            "BOL" to "Bolívar",
            "BOY" to "Boyacá",
            "CAL" to "Caldas",
            "CAQ" to "Caquetá",
            "CAS" to "Casanare",
            "CAU" to "Cauca",
            "CES" to "Cesar",
            "COR" to "Córdoba",
            "CUN" to "Cundinamarca",
            "CHO" to "Chocó",
            "GUA" to "Guainía",
            "GUV" to "Guaviare",
            "HUI" to "Huila",
            "LAG" to "La Guajira",
            "MAG" to "Magdalena",
            "MET" to "Meta",
            "NAR" to "Nariño",
            "NSA" to "Norte de Santander",
            "PUT" to "Putumayo",
            "QUI" to "Quindío",
            "RIS" to "Risaralda",
            "SAP" to "San Andrés, Providencia y Santa Catalina",
            "SAN" to "Santander",
            "SUC" to "Sucre",
            "TOL" to "Tolima",
            "VAC" to "Valle del Cauca",
            "VAU" to "Vaupés",
            "VID" to "Vichada",
        ),
        "CR" to listOf(
            "Alajuela" to "Alajuela",
            "Cartago" to "Cartago",
            "Guanacaste" to "Guanacaste",
            "Heredia" to "Heredia",
            "Limón" to "Limón",
            "Puntarenas" to "Puntarenas",
            "San José" to "San José",
        ),
        "CV" to listOf(
            "Boa Vista" to "Boa Vista",
            "Brava" to "Brava",
            "Fogo" to "Fogo",
            "Maio" to "Maio",
            "Sal" to "Sal",
            "Santiago" to "Santiago",
            "Santo Antão" to "Santo Antão",
            "São Nicolau" to "São Nicolau",
            "São Vicente" to "São Vicente",
        ),
        "EG" to listOf(
            "أسوان" to "أسوان — Aswan Governorate",
            "أسيوط" to "أسيوط — Asyut Governorate",
            "الإسكندرية" to "الإسكندرية — Alexandria Governorate",
            "الإسماعيلية" to "الإسماعيلية — Ismailia Governorate",
            "الأقصر" to "الأقصر — Luxor Governorate",
            "البحر الأحمر" to "البحر الأحمر — Red Sea Governorate",
            "البحيرة" to "البحيرة — El Beheira Governorate",
            "الجيزة" to "الجيزة — Giza Governorate",
            "الدقهلية" to "الدقهلية — Dakahlia Governorate",
            "السويس" to "السويس — Suez Governorate",
            "الشرقية" to "الشرقية — Ash Sharqia Governorate",
            "الغربية" to "الغربية — Gharbia Governorate",
            "الفيوم" to "الفيوم — Faiyum Governorate",
            "القاهرة" to "القاهرة — Cairo Governorate",
            "القليوبية" to "القليوبية — Qalyubia Governorate",
            "المنوفية" to "المنوفية — Menofia Governorate",
            "المنيا" to "المنيا — Menia Governorate",
            "الوادي الجديد" to "الوادي الجديد — New Valley Governorate",
            "بني سويف" to "بني سويف — Beni Suef Governorate",
            "بورسعيد" to "بورسعيد — Port Said Governorate",
            "جنوب سيناء" to "جنوب سيناء — South Sinai Governorate",
            "دمياط" to "دمياط — Damietta Governorate",
            "سوهاج" to "سوهاج — Sohag Governorate",
            "شمال سيناء" to "شمال سيناء — North Sinai Governorate",
            "قنا" to "قنا — Qena Governorate",
            "كفر الشيخ" to "كفر الشيخ — Kafr El Sheikh Governorate",
            "مطروح" to "مطروح — Matrouh Governorate",
        ),
        "ES" to listOf(
            "VI" to "Álava",
            "AB" to "Albacete",
            "A" to "Alicante",
            "AL" to "Almería",
            "O" to "Asturias",
            "AV" to "Ávila",
            "BA" to "Badajoz",
            "B" to "Barcelona",
            "BU" to "Burgos",
            "CC" to "Cáceres",
            "CA" to "Cádiz",
            "S" to "Cantabria",
            "CS" to "Castellón",
            "CE" to "Ceuta",
            "CR" to "Ciudad Real",
            "CO" to "Córdoba",
            "CU" to "Cuenca",
            "GI" to "Girona",
            "GR" to "Granada",
            "GU" to "Guadalajara",
            "SS" to "Guipúzcoa",
            "H" to "Huelva",
            "HU" to "Huesca",
            "PM" to "Islas Baleares",
            "J" to "Jaén",
            "C" to "La Coruña",
            "LO" to "La Rioja",
            "GC" to "Las Palmas",
            "LE" to "León",
            "L" to "Lérida",
            "LU" to "Lugo",
            "M" to "Madrid",
            "MA" to "Málaga",
            "ML" to "Melilla",
            "MU" to "Murcia",
            "NA" to "Navarra",
            "OR" to "Ourense",
            "P" to "Palencia",
            "PO" to "Pontevedra",
            "SA" to "Salamanca",
            "TF" to "Santa Cruz de Tenerife",
            "SG" to "Segovia",
            "SE" to "Sevilla",
            "SO" to "Soria",
            "T" to "Tarragona",
            "TE" to "Teruel",
            "TO" to "Toledo",
            "V" to "Valencia",
            "VA" to "Valladolid",
            "BI" to "Vizcaya",
            "ZA" to "Zamora",
            "Z" to "Zaragoza",
        ),
        "HK" to listOf(
            "Kowloon" to "九龍 - Kowloon",
            "Hong Kong Island" to "香港島 - Hong Kong Island",
            "New Territories" to "新界 - New Territories",
        ),
        "HN" to listOf(
            "Atlántida" to "Atlántida",
            "Choluteca" to "Choluteca",
            "Colón" to "Colón",
            "Comayagua" to "Comayagua",
            "Copán" to "Copán",
            "Cortés" to "Cortés",
            "El Paraíso" to "El Paraíso",
            "Francisco Morazán" to "Francisco Morazán",
            "Gracias a Dios" to "Gracias a Dios",
            "Intibucá" to "Intibucá",
            "Islas de la Bahía" to "Islas de la Bahía",
            "La Paz" to "La Paz",
            "Lempira" to "Lempira",
            "Ocotepeque" to "Ocotepeque",
            "Olancho" to "Olancho",
            "Santa Bárbara" to "Santa Bárbara",
            "Valle" to "Valle",
            "Yoro" to "Yoro",
        ),
        "ID" to listOf(
            "Aceh" to "Aceh — Aceh",
            "Bali" to "Bali — Bali",
            "Banten" to "Banten — Banten",
            "Bengkulu" to "Bengkulu — Bengkulu",
            "Daerah Istimewa Yogyakarta" to "Daerah Istimewa Yogyakarta — Special Region of Yogyakarta",
            "DKI Jakarta" to "DKI Jakarta — Jakarta",
            "Gorontalo" to "Gorontalo — Gorontalo",
            "Jambi" to "Jambi — Jambi",
            "Jawa Barat" to "Jawa Barat — West Java",
            "Jawa Tengah" to "Jawa Tengah — Central Java",
            "Jawa Timur" to "Jawa Timur — East Java",
            "Kalimantan Barat" to "Kalimantan Barat — West Kalimantan",
            "Kalimantan Selatan" to "Kalimantan Selatan — South Kalimantan",
            "Kalimantan Tengah" to "Kalimantan Tengah — Central Kalimantan",
            "Kalimantan Timur" to "Kalimantan Timur — East Kalimantan",
            "Kalimantan Utara" to "Kalimantan Utara — North Kalimantan",
            "Kepulauan Bangka Belitung" to "Kepulauan Bangka Belitung — Bangka Belitung Islands",
            "Kepulauan Riau" to "Kepulauan Riau — Riau Islands",
            "Lampung" to "Lampung — Lampung",
            "Maluku" to "Maluku — Maluku",
            "Maluku Utara" to "Maluku Utara — North Maluku",
            "Nusa Tenggara Barat" to "Nusa Tenggara Barat — West Nusa Tenggara",
            "Nusa Tenggara Timur" to "Nusa Tenggara Timur — East Nusa Tenggara",
            "Papua" to "Papua — Papua",
            "Papua Barat" to "Papua Barat — West Papua",
            "Riau" to "Riau — Riau",
            "Sulawesi Barat" to "Sulawesi Barat — West Sulawesi",
            "Sulawesi Selatan" to "Sulawesi Selatan — South Sulawesi",
            "Sulawesi Tengah" to "Sulawesi Tengah — Central Sulawesi",
            "Sulawesi Tenggara" to "Sulawesi Tenggara — South East Sulawesi",
            "Sulawesi Utara" to "Sulawesi Utara — North Sulawesi",
            "Sumatera Barat" to "Sumatera Barat — West Sumatra",
            "Sumatera Selatan" to "Sumatera Selatan — South Sumatra",
            "Sumatera Utara" to "Sumatera Utara — North Sumatra",
        ),
        "IE" to listOf(
            "County Carlow" to "County Carlow",
            "County Cavan" to "County Cavan",
            "County Clare" to "County Clare",
            "County Cork" to "County Cork",
            "County Donegal" to "County Donegal",
            "County Dublin" to "County Dublin",
            "County Galway" to "County Galway",
            "County Kerry" to "County Kerry",
            "County Kildare" to "County Kildare",
            "County Kilkenny" to "County Kilkenny",
            "County Laois" to "County Laois",
            "County Leitrim" to "County Leitrim",
            "County Limerick" to "County Limerick",
            "County Longford" to "County Longford",
            "County Louth" to "County Louth",
            "County Mayo" to "County Mayo",
            "County Meath" to "County Meath",
            "County Monaghan" to "County Monaghan",
            "County Offaly" to "County Offaly",
            "County Roscommon" to "County Roscommon",
            "County Sligo" to "County Sligo",
            "County Tipperary" to "County Tipperary",
            "County Waterford" to "County Waterford",
            "County Westmeath" to "County Westmeath",
            "County Wexford" to "County Wexford",
            "County Wicklow" to "County Wicklow",
        ),
        "IN" to listOf(
            "Andaman and Nicobar Islands" to "Andaman & Nicobar",
            "Andhra Pradesh" to "Andhra Pradesh",
            "Arunachal Pradesh" to "Arunachal Pradesh",
            "Assam" to "Assam",
            "Bihar" to "Bihar",
            "Chandigarh" to "Chandigarh",
            "Chhattisgarh" to "Chhattisgarh",
            "Dadra and Nagar Haveli and Daman and Diu" to "Dadra & Nagar Haveli & Daman & Diu",
            "Delhi" to "Delhi",
            "Goa" to "Goa",
            "Gujarat" to "Gujarat",
            "Haryana" to "Haryana",
            "Himachal Pradesh" to "Himachal Pradesh",
            "Jammu and Kashmir" to "Jammu & Kashmir",
            "Jharkhand" to "Jharkhand",
            "Karnataka" to "Karnataka",
            "Kerala" to "Kerala",
            "Ladakh" to "Ladakh",
            "Lakshadweep" to "Lakshadweep",
            "Madhya Pradesh" to "Madhya Pradesh",
            "Maharashtra" to "Maharashtra",
            "Manipur" to "Manipur",
            "Meghalaya" to "Meghalaya",
            "Mizoram" to "Mizoram",
            "Nagaland" to "Nagaland",
            "Odisha" to "Odisha",
            "Puducherry" to "Puducherry",
            "Punjab" to "Punjab",
            "Rajasthan" to "Rajasthan",
            "Sikkim" to "Sikkim",
            "Tamil Nadu" to "Tamil Nadu",
            "Telangana" to "Telangana",
            "Tripura" to "Tripura",
            "Uttar Pradesh" to "Uttar Pradesh",
            "Uttarakhand" to "Uttarakhand",
            "West Bengal" to "West Bengal",
        ),
        "IT" to listOf(
            "AG" to "Agrigento",
            "AL" to "Alessandria",
            "AN" to "Ancona",
            "AO" to "Aosta",
            "AR" to "Arezzo",
            "AP" to "Ascoli Piceno",
            "AT" to "Asti",
            "AV" to "Avellino",
            "BA" to "Bari",
            "BT" to "Barletta-Andria-Trani",
            "BL" to "Belluno",
            "BN" to "Benevento",
            "BG" to "Bergamo",
            "BI" to "Biella",
            "BO" to "Bologna",
            "BZ" to "Bolzano",
            "BS" to "Brescia",
            "BR" to "Brindisi",
            "CA" to "Cagliari",
            "CL" to "Caltanissetta",
            "CB" to "Campobasso",
            "CE" to "Caserta",
            "CT" to "Catania",
            "CZ" to "Catanzaro",
            "CH" to "Chieti",
            "CO" to "Como",
            "CS" to "Cosenza",
            "CR" to "Cremona",
            "KR" to "Crotone",
            "CN" to "Cuneo",
            "EN" to "Enna",
            "FM" to "Fermo",
            "FE" to "Ferrara",
            "FI" to "Firenze",
            "FG" to "Foggia",
            "FC" to "Forlì-Cesena",
            "FR" to "Frosinone",
            "GE" to "Genova",
            "GO" to "Gorizia",
            "GR" to "Grosseto",
            "IM" to "Imperia",
            "IS" to "Isernia",
            "AQ" to "L'Aquila",
            "SP" to "La Spezia",
            "LT" to "Latina",
            "LE" to "Lecce",
            "LC" to "Lecco",
            "LI" to "Livorno",
            "LO" to "Lodi",
            "LU" to "Lucca",
            "MC" to "Macerata",
            "MN" to "Mantova",
            "MS" to "Massa-Carrara",
            "MT" to "Matera",
            "ME" to "Messina",
            "MI" to "Milano",
            "MO" to "Modena",
            "MB" to "Monza e Brianza",
            "NA" to "Napoli",
            "NO" to "Novara",
            "NU" to "Nuoro",
            "OR" to "Oristano",
            "PD" to "Padova",
            "PA" to "Palermo",
            "PR" to "Parma",
            "PV" to "Pavia",
            "PG" to "Perugia",
            "PU" to "Pesaro e Urbino",
            "PE" to "Pescara",
            "PC" to "Piacenza",
            "PI" to "Pisa",
            "PT" to "Pistoia",
            "PN" to "Pordenone",
            "PZ" to "Potenza",
            "PO" to "Prato",
            "RG" to "Ragusa",
            "RA" to "Ravenna",
            "RC" to "Reggio Calabria",
            "RE" to "Reggio Emilia",
            "RI" to "Rieti",
            "RN" to "Rimini",
            "RM" to "Roma",
            "RO" to "Rovigo",
            "SA" to "Salerno",
            "SS" to "Sassari",
            "SV" to "Savona",
            "SI" to "Siena",
            "SR" to "Siracusa",
            "SO" to "Sondrio",
            "SU" to "Sud Sardegna",
            "TA" to "Taranto",
            "TE" to "Teramo",
            "TR" to "Terni",
            "TO" to "Torino",
            "TP" to "Trapani",
            "TN" to "Trento",
            "TV" to "Treviso",
            "TS" to "Trieste",
            "UD" to "Udine",
            "VA" to "Varese",
            "VE" to "Venezia",
            "VB" to "Verbano-Cusio-Ossola",
            "VC" to "Vercelli",
            "VR" to "Verona",
            "VV" to "Vibo Valentia",
            "VI" to "Vicenza",
            "VT" to "Viterbo",
        ),
        "JM" to listOf(
            "Clarendon" to "Clarendon",
            "Hanover" to "Hanover",
            "Kingston" to "Kingston",
            "Manchester" to "Manchester",
            "Portland" to "Portland",
            "St. Andrew" to "St. Andrew",
            "St. Ann" to "St. Ann",
            "St. Catherine" to "St. Catherine",
            "St. Elizabeth" to "St. Elizabeth",
            "St. James" to "St. James",
            "St. Mary" to "St. Mary",
            "St. Thomas" to "St. Thomas",
            "Trelawny" to "Trelawny",
            "Westmoreland" to "Westmoreland",
        ),
        "JP" to listOf(
            "北海道" to "北海道 — Hokkaido",
            "青森県" to "青森県 — Aomori",
            "岩手県" to "岩手県 — Iwate",
            "宮城県" to "宮城県 — Miyagi",
            "秋田県" to "秋田県 — Akita",
            "山形県" to "山形県 — Yamagata",
            "福島県" to "福島県 — Fukushima",
            "茨城県" to "茨城県 — Ibaraki",
            "栃木県" to "栃木県 — Tochigi",
            "群馬県" to "群馬県 — Gunma",
            "埼玉県" to "埼玉県 — Saitama",
            "千葉県" to "千葉県 — Chiba",
            "東京都" to "東京都 — Tokyo",
            "神奈川県" to "神奈川県 — Kanagawa",
            "新潟県" to "新潟県 — Niigata",
            "富山県" to "富山県 — Toyama",
            "石川県" to "石川県 — Ishikawa",
            "福井県" to "福井県 — Fukui",
            "山梨県" to "山梨県 — Yamanashi",
            "長野県" to "長野県 — Nagano",
            "岐阜県" to "岐阜県 — Gifu",
            "静岡県" to "静岡県 — Shizuoka",
            "愛知県" to "愛知県 — Aichi",
            "三重県" to "三重県 — Mie",
            "滋賀県" to "滋賀県 — Shiga",
            "京都府" to "京都府 — Kyoto",
            "大阪府" to "大阪府 — Osaka",
            "兵庫県" to "兵庫県 — Hyogo",
            "奈良県" to "奈良県 — Nara",
            "和歌山県" to "和歌山県 — Wakayama",
            "鳥取県" to "鳥取県 — Tottori",
            "島根県" to "島根県 — Shimane",
            "岡山県" to "岡山県 — Okayama",
            "広島県" to "広島県 — Hiroshima",
            "山口県" to "山口県 — Yamaguchi",
            "徳島県" to "徳島県 — Tokushima",
            "香川県" to "香川県 — Kagawa",
            "愛媛県" to "愛媛県 — Ehime",
            "高知県" to "高知県 — Kochi",
            "福岡県" to "福岡県 — Fukuoka",
            "佐賀県" to "佐賀県 — Saga",
            "長崎県" to "長崎県 — Nagasaki",
            "熊本県" to "熊本県 — Kumamoto",
            "大分県" to "大分県 — Oita",
            "宮崎県" to "宮崎県 — Miyazaki",
            "鹿児島県" to "鹿児島県 — Kagoshima",
            "沖縄県" to "沖縄県 — Okinawa",
        ),
        "KI" to listOf(
            "Gilbert Islands" to "Gilbert Islands",
            "Line Islands" to "Line Islands",
            "Phoenix Islands" to "Phoenix Islands",
        ),
        "KN" to listOf(
            "Nevis" to "Nevis",
            "St. Kitts" to "St. Kitts",
        ),
        "KR" to listOf(
            "강원도" to "강원 — Gangwon-do",
            "경기도" to "경기 — Gyeonggi-do",
            "경상남도" to "경남 — Gyeongsangnam-do",
            "경상북도" to "경북 — Gyeongsangbuk-do",
            "광주광역시" to "광주 — Gwangju",
            "대구광역시" to "대구 — Daegu",
            "대전광역시" to "대전 — Daejeon",
            "부산광역시" to "부산 — Busan",
            "서울특별시" to "서울 — Seoul",
            "세종특별자치시" to "세종 — Sejong",
            "울산광역시" to "울산 — Ulsan",
            "인천광역시" to "인천 — Incheon",
            "전라남도" to "전남 — Jeollanam-do",
            "전라북도" to "전북 — Jeollabuk-do",
            "제주특별자치도" to "제주 — Jeju-do",
            "충청남도" to "충남 — Chungcheongnam-do",
            "충청북도" to "충북 — Chungcheongbuk-do",
        ),
        "KY" to listOf(
            "Cayman Brac" to "Cayman Brac",
            "Grand Cayman" to "Grand Cayman",
            "Little Cayman" to "Little Cayman",
        ),
        "KZ" to listOf(
            "Almaty" to "Almaty",
            "Astana" to "Astana",
            "Almatinskaya oblast'" to "Almatinskaya oblast'",
            "Akmolinskaya oblast'" to "Akmolinskaya oblast'",
            "Aktyubinskaya oblast'" to "Aktyubinskaya oblast'",
            "Atyrauskaya oblast'" to "Atyrauskaya oblast'",
            "Baykonyr" to "Baykonyr",
            "Zapadno-Kazakhstanskaya oblast'" to "Zapadno-Kazakhstanskaya oblast'",
            "Mangistauskaya oblast'" to "Mangistauskaya oblast'",
            "Yuzhno-Kazakhstankaya oblast'" to "Yuzhno-Kazakhstankaya oblast'",
            "Pavlodarskaya oblast'" to "Pavlodarskaya oblast'",
            "Karagandinskaya oblast'" to "Karagandinskaya oblast'",
            "Kostanayskaya oblast'" to "Kostanayskaya oblast'",
            "Kyzylordinskaya oblast'" to "Kyzylordinskaya oblast'",
            "Vostochno-Kazakhstanskaya oblast'" to "Vostochno-Kazakhstanskaya oblast'",
            "Severo-Kazakhstanskaya oblast'" to "Severo-Kazakhstanskaya oblast'",
            "Zhambylskaya oblast'" to "Zhambylskaya oblast'",
        ),
        "MN" to listOf(
            "Ulaanbaatar" to "Ulaanbaatar",
            "Arkhangai Province" to "Arkhangai Province",
            "Bayankhongor Province" to "Bayankhongor Province",
            "Bayan-Ölgii Province" to "Bayan-Ölgii Province",
            "Bulgan Province" to "Bulgan Province",
            "Darkhan-Uul Province" to "Darkhan-Uul Province",
            "Dornod Province" to "Dornod Province",
            "Dornogovi Province" to "Dornogovi Province",
            "Dundgovi Province" to "Dundgovi Province",
            "Zavkhan Province" to "Zavkhan Province",
            "Govi-Altai Province" to "Govi-Altai Province",
            "Govisümber Province" to "Govisümber Province",
            "Khentii Province" to "Khentii Province",
            "Khovd Province" to "Khovd Province",
            "Khövsgöl Province" to "Khövsgöl Province",
            "Ömnögovi Province" to "Ömnögovi Province",
            "Orkhon Province" to "Orkhon Province",
            "Övörkhangai Province" to "Övörkhangai Province",
            "Selenge Province" to "Selenge Province",
            "Sükhbaatar Province" to "Sükhbaatar Province",
            "Töv Province" to "Töv Province",
            "Uvs Province" to "Uvs Province",
        ),
        "MX" to listOf(
            "Ags." to "Aguascalientes",
            "B.C." to "Baja California",
            "B.C.S." to "Baja California Sur",
            "Camp." to "Campeche",
            "Chis." to "Chiapas",
            "Chih." to "Chihuahua",
            "CDMX" to "Ciudad de México",
            "Coah." to "Coahuila de Zaragoza",
            "Col." to "Colima",
            "Dgo." to "Durango",
            "Méx." to "Estado de México",
            "Gto." to "Guanajuato",
            "Gro." to "Guerrero",
            "Hgo." to "Hidalgo",
            "Jal." to "Jalisco",
            "Mich." to "Michoacán",
            "Mor." to "Morelos",
            "Nay." to "Nayarit",
            "N.L." to "Nuevo León",
            "Oax." to "Oaxaca",
            "Pue." to "Puebla",
            "Qro." to "Querétaro",
            "Q.R." to "Quintana Roo",
            "S.L.P." to "San Luis Potosí",
            "Sin." to "Sinaloa",
            "Son." to "Sonora",
            "Tab." to "Tabasco",
            "Tamps." to "Tamaulipas",
            "Tlax." to "Tlaxcala",
            "Ver." to "Veracruz",
            "Yuc." to "Yucatán",
            "Zac." to "Zacatecas",
        ),
        "MY" to listOf(
            "Johor" to "Johor",
            "Kedah" to "Kedah",
            "Kelantan" to "Kelantan",
            "Kuala Lumpur" to "Kuala Lumpur",
            "Labuan" to "Labuan",
            "Melaka" to "Melaka",
            "Negeri Sembilan" to "Negeri Sembilan",
            "Pahang" to "Pahang",
            "Perak" to "Perak",
            "Perlis" to "Perlis",
            "Pulau Pinang" to "Pulau Pinang",
            "Putrajaya" to "Putrajaya",
            "Sabah" to "Sabah",
            "Sarawak" to "Sarawak",
            "Selangor" to "Selangor",
            "Terengganu" to "Terengganu",
        ),
        "MZ" to listOf(
            "Cabo Delgado" to "Cabo Delgado",
            "Cidade de Maputo" to "Cidade de Maputo",
            "Gaza" to "Gaza",
            "Inhambane" to "Inhambane",
            "Manica" to "Manica",
            "Maputo" to "Maputo",
            "Nampula" to "Nampula",
            "Niassa" to "Niassa",
            "Sofala" to "Sofala",
            "Tete" to "Tete",
            "Zambezia" to "Zambezia",
        ),
        "NG" to listOf(
            "Abia" to "Abia",
            "Adamawa" to "Adamawa",
            "Akwa Ibom" to "Akwa Ibom",
            "Anambra" to "Anambra",
            "Bauchi" to "Bauchi",
            "Bayelsa" to "Bayelsa",
            "Benue" to "Benue",
            "Borno" to "Borno",
            "Cross River" to "Cross River",
            "Delta" to "Delta",
            "Ebonyi" to "Ebonyi",
            "Edo" to "Edo",
            "Ekiti" to "Ekiti",
            "Enugu" to "Enugu",
            "Federal Capital Territory" to "Federal Capital Territory",
            "Gombe" to "Gombe",
            "Imo" to "Imo",
            "Jigawa" to "Jigawa",
            "Kaduna" to "Kaduna",
            "Kano" to "Kano",
            "Katsina" to "Katsina",
            "Kebbi" to "Kebbi",
            "Kogi" to "Kogi",
            "Kwara" to "Kwara",
            "Lagos" to "Lagos",
            "Nasarawa" to "Nasarawa",
            "Niger" to "Niger",
            "Ogun State" to "Ogun State",
            "Ondo" to "Ondo",
            "Osun" to "Osun",
            "Oyo" to "Oyo",
            "Plateau" to "Plateau",
            "Rivers" to "Rivers",
            "Sokoto" to "Sokoto",
            "Taraba" to "Taraba",
            "Yobe" to "Yobe",
            "Zamfara" to "Zamfara",
        ),
        "NI" to listOf(
            "Boaco" to "Boaco",
            "Carazo" to "Carazo",
            "Chinandega" to "Chinandega",
            "Chontales" to "Chontales",
            "Estelí" to "Estelí",
            "Granada" to "Granada",
            "Jinotega" to "Jinotega",
            "León" to "León",
            "Madriz" to "Madriz",
            "Managua" to "Managua",
            "Masaya" to "Masaya",
            "Matagalpa" to "Matagalpa",
            "Nueva Segovia" to "Nueva Segovia",
            "Región Autónoma de la Costa Caribe Norte" to "Región Autónoma de la Costa Caribe Norte",
            "Región Autónoma de la Costa Caribe Sur" to "Región Autónoma de la Costa Caribe Sur",
            "Río San Juan" to "Río San Juan",
            "Rivas" to "Rivas",
        ),
        "NR" to listOf(
            "Aiwo District" to "Aiwo District",
            "Anabar District" to "Anabar District",
            "Anetan District" to "Anetan District",
            "Anibare District" to "Anibare District",
            "Baiti District" to "Baiti District",
            "Boe District" to "Boe District",
            "Buada District" to "Buada District",
            "Denigomodu District" to "Denigomodu District",
            "Ewa District" to "Ewa District",
            "Ijuw District" to "Ijuw District",
            "Meneng District" to "Meneng District",
            "Nibok District" to "Nibok District",
            "Uaboe District" to "Uaboe District",
            "Yaren District" to "Yaren District",
        ),
        "PA" to listOf(
            "Bocas del Toro" to "Bocas del Toro",
            "Chiriquí" to "Chiriquí",
            "Coclé" to "Coclé",
            "Colón" to "Colón",
            "Darién" to "Darién",
            "Herrera" to "Herrera",
            "Los Santos" to "Los Santos",
            "Panamá" to "Panamá",
            "Veraguas" to "Veraguas",
            "Panamá Oeste" to "Panamá Oeste",
            "Emberá" to "Emberá",
            "Guna Yala" to "Guna Yala",
            "Ngäbe-Buglé" to "Ngäbe-Buglé",
        ),
        "PE" to listOf(
            "Municipalidad Metropolitana de Lima" to "Municipalidad Metropolitana de Lima",
            "Amazonas" to "Amazonas",
            "Ancash" to "Ancash",
            "Apurímac" to "Apurímac",
            "Arequipa" to "Arequipa",
            "Ayacucho" to "Ayacucho",
            "Cajamarca" to "Cajamarca",
            "Cusco" to "Cusco",
            "El Callao" to "El Callao",
            "Huancavelica" to "Huancavelica",
            "Huánuco" to "Huánuco",
            "Ica" to "Ica",
            "Junín" to "Junín",
            "La Libertad" to "La Libertad",
            "Lambayeque" to "Lambayeque",
            "Lima" to "Lima",
            "Loreto" to "Loreto",
            "Madre de Dios" to "Madre de Dios",
            "Moquegua" to "Moquegua",
            "Pasco" to "Pasco",
            "Piura" to "Piura",
            "Puno" to "Puno",
            "San Martín" to "San Martín",
            "Tacna" to "Tacna",
            "Tumbes" to "Tumbes",
            "Ucayali" to "Ucayali",
        ),
        "PF" to listOf(
            "Windward Islands" to "Windward Islands",
            "Austral Islands" to "Austral Islands",
            "Tuamotu-Gambier" to "Tuamotu-Gambier",
            "Leeward Islands" to "Leeward Islands",
            "Marquesas Islands" to "Marquesas Islands",
        ),
        "PG" to listOf(
            "National Capital District" to "National Capital District",
            "Central" to "Central",
            "Chimbu" to "Chimbu",
            "Eastern Highlands" to "Eastern Highlands",
            "East New Britain" to "East New Britain",
            "East Sepik" to "East Sepik",
            "Enga" to "Enga",
            "Gulf" to "Gulf",
            "Hela" to "Hela",
            "Jiwaka" to "Jiwaka",
            "Madang" to "Madang",
            "Manus" to "Manus",
            "Milne Bay" to "Milne Bay",
            "Morobe" to "Morobe",
            "New Ireland" to "New Ireland",
            "Northern" to "Northern",
            "West Sepik" to "West Sepik",
            "Southern Highlands" to "Southern Highlands",
            "Western" to "Western",
            "Western Highlands" to "Western Highlands",
            "West New Britain" to "West New Britain",
            "Bougainville" to "Bougainville",
        ),
        "PH" to listOf(
            "Abra" to "Abra",
            "Agusan del Norte" to "Agusan del Norte",
            "Agusan del Sur" to "Agusan del Sur",
            "Aklan" to "Aklan",
            "Albay" to "Albay",
            "Antique" to "Antique",
            "Apayao" to "Apayao",
            "Aurora" to "Aurora",
            "Basilan" to "Basilan",
            "Bataan" to "Bataan",
            "Batanes" to "Batanes",
            "Batangas" to "Batangas",
            "Benguet" to "Benguet",
            "Biliran" to "Biliran",
            "Bohol" to "Bohol",
            "Bukidnon" to "Bukidnon",
            "Bulacan" to "Bulacan",
            "Cagayan" to "Cagayan",
            "Camarines Norte" to "Camarines Norte",
            "Camarines Sur" to "Camarines Sur",
            "Camiguin" to "Camiguin",
            "Capiz" to "Capiz",
            "Catanduanes" to "Catanduanes",
            "Cavite" to "Cavite",
            "Cebu" to "Cebu",
            "Compostela Valley" to "Compostela Valley",
            "Cotabato" to "Cotabato",
            "Davao del Norte" to "Davao del Norte",
            "Davao del Sur" to "Davao del Sur",
            "Davao Occidental" to "Davao Occidental",
            "Davao Oriental" to "Davao Oriental",
            "Dinagat Islands" to "Dinagat Islands",
            "Eastern Samar" to "Eastern Samar",
            "Guimaras" to "Guimaras",
            "Ifugao" to "Ifugao",
            "Ilocos Norte" to "Ilocos Norte",
            "Ilocos Sur" to "Ilocos Sur",
            "Iloilo" to "Iloilo",
            "Isabela" to "Isabela",
            "Kalinga" to "Kalinga",
            "La Union" to "La Union",
            "Laguna" to "Laguna",
            "Lanao del Norte" to "Lanao del Norte",
            "Lanao del Sur" to "Lanao del Sur",
            "Leyte" to "Leyte",
            "Maguindanao" to "Maguindanao",
            "Marinduque" to "Marinduque",
            "Masbate" to "Masbate",
            "Metro Manila" to "Metro Manila",
            "Mindoro Occidental" to "Mindoro Occidental",
            "Mindoro Oriental" to "Mindoro Oriental",
            "Misamis Occidental" to "Misamis Occidental",
            "Misamis Oriental" to "Misamis Oriental",
            "Mountain Province" to "Mountain Province",
            "Negros Occidental" to "Negros Occidental",
            "Negros Oriental" to "Negros Oriental",
            "Northern Samar" to "Northern Samar",
            "Nueva Ecija" to "Nueva Ecija",
            "Nueva Vizcaya" to "Nueva Vizcaya",
            "Palawan" to "Palawan",
            "Pampanga" to "Pampanga",
            "Pangasinan" to "Pangasinan",
            "Quezon Province" to "Quezon Province",
            "Quirino" to "Quirino",
            "Rizal" to "Rizal",
            "Romblon" to "Romblon",
            "Samar" to "Samar",
            "Sarangani" to "Sarangani",
            "Siquijor" to "Siquijor",
            "Sorsogon" to "Sorsogon",
            "South Cotabato" to "South Cotabato",
            "Southern Leyte" to "Southern Leyte",
            "Sultan Kudarat" to "Sultan Kudarat",
            "Sulu" to "Sulu",
            "Surigao del Norte" to "Surigao del Norte",
            "Surigao del Sur" to "Surigao del Sur",
            "Tarlac" to "Tarlac",
            "Tawi-Tawi" to "Tawi-Tawi",
            "Zambales" to "Zambales",
            "Zamboanga del Norte" to "Zamboanga del Norte",
            "Zamboanga del Sur" to "Zamboanga del Sur",
            "Zamboanga Sibuguey" to "Zamboanga Sibuguey",
        ),
        "RU" to listOf(
            "Алтайский край" to "Алтайский край — Altayskiy kray",
            "Амурская область" to "Амурская область — Amurskaya oblast'",
            "Архангельская область" to "Архангельская область — Arkhangelskaya oblast'",
            "Астраханская область" to "Астраханская область — Astrakhanskaya oblast'",
            "Белгородская область" to "Белгородская область — Belgorodskaya oblast'",
            "Брянская область" to "Брянская область — Bryanskaya oblast'",
            "Владимирская область" to "Владимирская область — Vladimirskaya oblast'",
            "Волгоградская область" to "Волгоградская область — Volgogradskaya oblast'",
            "Вологодская область" to "Вологодская область — Vologodskaya oblast'",
            "Воронежская область" to "Воронежская область — Voronezhskaya oblast'",
            "Еврейская автономная область" to "Еврейская автономная область — Evreyskaya avtonomnaya oblast'",
            "Забайкальский край" to "Забайкальский край — Zabaykalskiy kray",
            "Ивановская область" to "Ивановская область — Ivanovskaya oblast'",
            "Иркутская область" to "Иркутская область — Irkutskaya oblast'",
            "Кабардино-Балкарская Республика" to "Кабардино-Балкарская Республика — Kabardino-Balkarskaya Republits",
            "Калининградская область" to "Калининградская область — Kaliningradskaya oblast'",
            "Калужская область" to "Калужская область — Kaluzhskaya oblast'",
            "Камчатский край" to "Камчатский край — Kamchatskiy kray",
            "Карачаево-Черкесская Республика" to "Карачаево-Черкесская Республика — Karachaevo-Cherkesskaya Republits",
            "Кемеровская область" to "Кемеровская область — Kemerovskaya oblast'",
            "Кировская область" to "Кировская область — Kirovskaya oblast'",
            "Костромская область" to "Костромская область — Kostromskaya oblast'",
            "Краснодарский край" to "Краснодарский край — Krasnodarskiy kray",
            "Красноярский край" to "Красноярский край — Krasnoyarskiy kray",
            "Курганская область" to "Курганская область — Kurganskaya oblast'",
            "Курская область" to "Курская область — Kurskaya oblast'",
            "Ленинградская область" to "Ленинградская область — Leningradskaya oblast'",
            "Липецкая область" to "Липецкая область — Lipetskaya oblast'",
            "Магаданская область" to "Магаданская область — Magadanskaya oblast'",
            "Москва" to "Москва — Moskva",
            "Московская область" to "Московская область — Moskovskaya oblast'",
            "Мурманская область" to "Мурманская область — Murmanskaya oblast'",
            "Ненецкий автономный округ" to "Ненецкий автономный округ — Nenetskiy",
            "Нижегородская область" to "Нижегородская область — Nizhegorodskaya oblast'",
            "Новгородская область" to "Новгородская область — Novgorodskaya oblast'",
            "Новосибирская область" to "Новосибирская область — Novosibirskaya oblast'",
            "Омская область" to "Омская область — Omskaya oblast'",
            "Оренбургская область" to "Оренбургская область — Orenburgskaya oblast'",
            "Орловская область" to "Орловская область — Orlovskaya oblast'",
            "Пензенская область" to "Пензенская область — Penzenskaya oblast'",
            "Пермский край" to "Пермский край — Permskiy kray",
            "Приморский край" to "Приморский край — Primorskiy kray",
            "Псковская область" to "Псковская область — Pskovskaya oblast'",
            "Республика Адыгея" to "Республика Адыгея — Respublika Adygeya",
            "Республика Алтай" to "Республика Алтай — Altay Republits",
            "Республика Башкортостан" to "Республика Башкортостан — Bashkortostan Republits",
            "Республика Бурятия" to "Республика Бурятия — Buryatiya Republits",
            "Республика Дагестан" to "Республика Дагестан — Dagestan Republits",
            "Республика Ингушетия" to "Республика Ингушетия — Ingushetiya Republits",
            "Республика Калмыкия" to "Республика Калмыкия — Respublika Kalmykiya",
            "Республика Карелия" to "Республика Карелия — Kareliya Republits",
            "Республика Коми" to "Республика Коми — Komi Republits",
            "Республика Марий Эл" to "Республика Марий Эл — Respublika Mariy El",
            "Республика Мордовия" to "Республика Мордовия — Respublika Mordoviya",
            "Республика Саха (Якутия)" to "Республика Саха (Якутия) — Sakha (Yakutiya) Republits",
            "Республика Северная Осетия-Алания" to "Республика Северная Осетия-Алания — Respublika Severnaya Osetiya-Alaniya",
            "Республика Татарстан" to "Республика Татарстан — Respublika Tatarstan",
            "Республика Тыва" to "Республика Тыва — Tyva Republits",
            "Республика Удмуртия" to "Республика Удмуртия — Udmurtskaja Respublika",
            "Республика Хакасия" to "Республика Хакасия — Khakasiya Republits",
            "Ростовская область" to "Ростовская область — Rostovskaya oblast'",
            "Рязанская область" to "Рязанская область — Ryazanskaya oblast'",
            "Самарская область" to "Самарская область — Samarskaya oblast'",
            "Санкт-Петербург" to "Санкт-Петербург — Sankt-Peterburg",
            "Саратовская область" to "Саратовская область — Saratovskaya oblast'",
            "Сахалинская область" to "Сахалинская область — Sakhalinskaya oblast'",
            "Свердловская область" to "Свердловская область — Sverdlovskaya oblast'",
            "Смоленская область" to "Смоленская область — Smolenskaya oblast'",
            "Ставропольский край" to "Ставропольский край — Stavropolskiy kray",
            "Тамбовская область" to "Тамбовская область — Tambovskaya oblast'",
            "Тверская область" to "Тверская область — Tverskaya oblast'",
            "Томская область" to "Томская область — Tomskaya oblast'",
            "Тульская область" to "Тульская область — Tulskaya oblast'",
            "Тюменская область" to "Тюменская область — Tyumenskaya oblast'",
            "Ульяновская область" to "Ульяновская область — Ulyanovskaya oblast'",
            "Хабаровский край" to "Хабаровский край — Khabarovskiy kray",
            "Ханты-Мансийский автономный округ" to "Ханты-Мансийский автономный округ — Khanty-Mansiyskiy avtonomnyy okrug",
            "Челябинская область" to "Челябинская область — Chelyabinskaya oblast'",
            "Чеченская Республика" to "Чеченская Республика — Chechenskaya Republits",
            "Чувашская Республика" to "Чувашская Республика — Chuvashia",
            "Чукотский автономный округ" to "Чукотский автономный округ — Chukotskiy",
            "Ямало-Ненецкий автономный округ" to "Ямало-Ненецкий автономный округ — Yamalo-Nenetskiy",
            "Ярославская область" to "Ярославская область — Yaroslavskaya oblast'",
        ),
        "SR" to listOf(
            "Brokopondo" to "Brokopondo",
            "Commewijne" to "Commewijne",
            "Coronie" to "Coronie",
            "Marowijne" to "Marowijne",
            "Nickerie" to "Nickerie",
            "Para" to "Para",
            "Paramaribo" to "Paramaribo",
            "Saramacca" to "Saramacca",
            "Sipaliwini" to "Sipaliwini",
            "Wanica" to "Wanica",
        ),
        "SV" to listOf(
            "Ahuachapan" to "Ahuachapán",
            "Cabanas" to "Cabañas",
            "Calatenango" to "Chalatenango",
            "Cuscatlan" to "Cuscatlán",
            "La Libertad" to "La Libertad",
            "La Paz" to "La Paz",
            "La Union" to "La Unión",
            "Morazan" to "Morazán",
            "San Miguel" to "San Miguel",
            "San Salvador" to "San Salvador",
            "San Vicente" to "San Vicente",
            "Santa Ana" to "Santa Ana",
            "Sonsonate" to "Sonsonate",
            "Usulutan" to "Usulután",
        ),
        "TH" to listOf(
            "กระบี่" to "กระบี่ — Krabi",
            "กรุงเทพมหานคร" to "กรุงเทพมหานคร — Bangkok",
            "กาญจนบุรี" to "กาญจนบุรี — Kanchanaburi",
            "กาฬสินธุ์" to "กาฬสินธุ์ — Kalasin",
            "กำแพงเพชร" to "กำแพงเพชร — Kamphaeng Phet",
            "ขอนแก่น" to "ขอนแก่น — Khon Kaen",
            "จังหวัด บึงกาฬ" to "จังหวัด บึงกาฬ — Bueng Kan",
            "จันทบุรี" to "จันทบุรี — Chanthaburi",
            "ฉะเชิงเทรา" to "ฉะเชิงเทรา — Chachoengsao",
            "ชลบุรี" to "ชลบุรี — Chon Buri",
            "ชัยนาท" to "ชัยนาท — Chai Nat",
            "ชัยภูมิ" to "ชัยภูมิ — Chaiyaphum",
            "ชุมพร" to "ชุมพร — Chumpon",
            "เชียงราย" to "เชียงราย — Chiang Rai",
            "เชียงใหม่" to "เชียงใหม่ — Chiang Mai",
            "ตรัง" to "ตรัง — Trang",
            "ตราด" to "ตราด — Trat",
            "ตาก" to "ตาก — Tak",
            "นครนายก" to "นครนายก — Nakhon Nayok",
            "นครปฐม" to "นครปฐม — Nakhon Pathom",
            "นครพนม" to "นครพนม — Nakhon Phanom",
            "นครราชสีมา" to "นครราชสีมา — Nakhon Ratchasima",
            "นครศรีธรรมราช" to "นครศรีธรรมราช — Nakhon Si Thammarat",
            "นครสวรรค์" to "นครสวรรค์ — Nakhon Sawan",
            "นนทบุรี" to "นนทบุรี — Nonthaburi",
            "นราธิวาส" to "นราธิวาส — Narathiwat",
            "น่าน" to "น่าน — Nan",
            "บุรีรัมย์" to "บุรีรัมย์ — Buri Ram",
            "ปทุมธานี" to "ปทุมธานี — Pathum Thani",
            "ประจวบคีรีขันธ์" to "ประจวบคีรีขันธ์ — Prachuap Khiri Khan",
            "ปราจีนบุรี" to "ปราจีนบุรี — Prachin Buri",
            "ปัตตานี" to "ปัตตานี — Pattani",
            "พระนครศรีอยุธยา" to "พระนครศรีอยุธยา — Phra Nakhon Si Ayutthaya",
            "พะเยา" to "พะเยา — Phayao",
            "พังงา" to "พังงา — Phang Nga",
            "พัทลุง" to "พัทลุง — Phattalung",
            "พิจิตร" to "พิจิตร — Phichit",
            "พิษณุโลก" to "พิษณุโลก — Phitsanulok",
            "เพชรบุรี" to "เพชรบุรี — Phetchaburi",
            "เพชรบูรณ์" to "เพชรบูรณ์ — Phetchabun",
            "แพร่" to "แพร่ — Phrae",
            "ภูเก็ต" to "ภูเก็ต — Phuket",
            "มหาสารคาม" to "มหาสารคาม — Maha Sarakham",
            "มุกดาหาร" to "มุกดาหาร — Mukdahan",
            "แม่ฮ่องสอน" to "แม่ฮ่องสอน — Mae Hong Son",
            "ยโสธร" to "ยโสธร — Yasothon",
            "ยะลา" to "ยะลา — Yala",
            "ร้อยเอ็ด" to "ร้อยเอ็ด — Roi Et",
            "ระนอง" to "ระนอง — Ranong",
            "ระยอง" to "ระยอง — Rayong",
            "ราชบุรี" to "ราชบุรี — Ratchaburi",
            "ลพบุรี" to "ลพบุรี — Lop Buri",
            "ลำปาง" to "ลำปาง — Lampang",
            "ลำพูน" to "ลำพูน — Lamphun",
            "เลย" to "เลย — Loei",
            "ศรีสะเกษ" to "ศรีสะเกษ — Si Sa Ket",
            "สกลนคร" to "สกลนคร — Sakon Nakhon",
            "สงขลา" to "สงขลา — Songkhla",
            "สตูล" to "สตูล — Satun",
            "สมุทรปราการ" to "สมุทรปราการ — Samut Prakan",
            "สมุทรสงคราม" to "สมุทรสงคราม — Samut Songkhram",
            "สมุทรสาคร" to "สมุทรสาคร — Samut Sakhon",
            "สระแก้ว" to "สระแก้ว — Sa Kaeo",
            "สระบุรี" to "สระบุรี — Saraburi",
            "สิงห์บุรี" to "สิงห์บุรี — Sing Buri",
            "สุโขทัย" to "สุโขทัย — Sukhothai",
            "สุพรรณบุรี" to "สุพรรณบุรี — Suphanburi",
            "สุราษฎร์ธานี" to "สุราษฎร์ธานี — Surat Thani",
            "สุรินทร์" to "สุรินทร์ — Surin",
            "หนองคาย" to "หนองคาย — Nong Khai",
            "หนองบัวลำภู" to "หนองบัวลำภู — Nong Bua Lam Phu",
            "อ่างทอง" to "อ่างทอง — Ang Thong",
            "อำนาจเจริญ" to "อำนาจเจริญ — Amnat Charoen",
            "อุดรธานี" to "อุดรธานี — Udon Thani",
            "อุตรดิตถ์" to "อุตรดิตถ์ — Uttaradit",
            "อุทัยธานี" to "อุทัยธานี — Uthai Thani",
            "อุบลราชธานี" to "อุบลราชธานี — Ubon Ratchathani",
        ),
        "TR" to listOf(
            "Adana" to "Adana",
            "Adıyaman" to "Adıyaman",
            "Afyon" to "Afyon",
            "Ağrı" to "Ağrı",
            "Aksaray" to "Aksaray",
            "Amasya" to "Amasya",
            "Ankara" to "Ankara",
            "Antalya" to "Antalya",
            "Ardahan" to "Ardahan",
            "Artvin" to "Artvin",
            "Aydın" to "Aydın",
            "Balıkesir" to "Balıkesir",
            "Bartın" to "Bartın",
            "Batman" to "Batman",
            "Bayburt" to "Bayburt",
            "Bilecik" to "Bilecik",
            "Bingöl" to "Bingöl",
            "Bitlis" to "Bitlis",
            "Bolu" to "Bolu",
            "Burdur" to "Burdur",
            "Bursa" to "Bursa",
            "Çanakkale" to "Çanakkale",
            "Çankırı" to "Çankırı",
            "Çorum" to "Çorum",
            "Denizli" to "Denizli",
            "Diyarbakır" to "Diyarbakır",
            "Düzce" to "Düzce",
            "Edirne" to "Edirne",
            "Elazığ" to "Elazığ",
            "Erzincan" to "Erzincan",
            "Erzurum" to "Erzurum",
            "Eskişehir" to "Eskişehir",
            "Gaziantep" to "Gaziantep",
            "Giresun" to "Giresun",
            "Gümüşhane" to "Gümüşhane",
            "Hakkari" to "Hakkari",
            "Hatay" to "Hatay",
            "Iğdır" to "Iğdır",
            "Isparta" to "Isparta",
            "İstanbul" to "İstanbul",
            "İzmir" to "İzmir",
            "Kahramanmaraş" to "Kahramanmaraş",
            "Karabük" to "Karabük",
            "Karaman" to "Karaman",
            "Kars" to "Kars",
            "Kastamonu" to "Kastamonu",
            "Kayseri" to "Kayseri",
            "Kırıkkale" to "Kırıkkale",
            "Kırklareli" to "Kırklareli",
            "Kırşehir" to "Kırşehir",
            "Kilis" to "Kilis",
            "Kocaeli" to "Kocaeli",
            "Konya" to "Konya",
            "Kütahya" to "Kütahya",
            "Malatya" to "Malatya",
            "Manisa" to "Manisa",
            "Mardin" to "Mardin",
            "Mersin" to "Mersin",
            "Muğla" to "Muğla",
            "Muş" to "Muş",
            "Nevşehir" to "Nevşehir",
            "Niğde" to "Niğde",
            "Ordu" to "Ordu",
            "Osmaniye" to "Osmaniye",
            "Rize" to "Rize",
            "Sakarya" to "Sakarya",
            "Samsun" to "Samsun",
            "Siirt" to "Siirt",
            "Sinop" to "Sinop",
            "Sivas" to "Sivas",
            "Şanlıurfa" to "Şanlıurfa",
            "Şırnak" to "Şırnak",
            "Tekirdağ" to "Tekirdağ",
            "Tokat" to "Tokat",
            "Trabzon" to "Trabzon",
            "Tunceli" to "Tunceli",
            "Uşak" to "Uşak",
            "Van" to "Van",
            "Yalova" to "Yalova",
            "Yozgat" to "Yozgat",
            "Zonguldak" to "Zonguldak",
        ),
        "TV" to listOf(
            "Funafuti" to "Funafuti",
            "Nanumanga" to "Nanumanga",
            "Nanumea" to "Nanumea",
            "Niulakita" to "Niulakita",
            "Niutao" to "Niutao",
            "Nui" to "Nui",
            "Nukufetau" to "Nukufetau",
            "Nukulaelae" to "Nukulaelae",
            "Vaitupu" to "Vaitupu",
        ),
        "TW" to listOf(
            "台中市" to "台中市 — Taichung City",
            "台北市" to "台北市 — Taipei City",
            "台東縣" to "台東縣 — Taitung County",
            "台南市" to "台南市 — Tainan City",
            "宜蘭縣" to "宜蘭縣 — Yilan County",
            "花蓮縣" to "花蓮縣 — Hualien County",
            "金門縣" to "金門縣 — Kinmen County",
            "南投縣" to "南投縣 — Nantou County",
            "屏東縣" to "屏東縣 — Pingtung County",
            "苗栗縣" to "苗栗縣 — Miaoli County",
            "桃園市" to "桃園市 — Taoyuan City",
            "高雄市" to "高雄市 — Kaohsiung City",
            "基隆市" to "基隆市 — Keelung City",
            "連江縣" to "連江縣 — Lienchiang County",
            "雲林縣" to "雲林縣 — Yunlin County",
            "新北市" to "新北市 — New Taipei City",
            "新竹市" to "新竹市 — Hsinchu City",
            "新竹縣" to "新竹縣 — Hsinchu County",
            "嘉義市" to "嘉義市 — Chiayi City",
            "嘉義縣" to "嘉義縣 — Chiayi County",
            "彰化縣" to "彰化縣 — Changhua County",
            "澎湖縣" to "澎湖縣 — Penghu County",
        ),
        "UA" to listOf(
            "Вінницька область" to "Вінницька область — Vinnyts'ka oblast",
            "Волинська область" to "Волинська область — Volyns'ka oblast",
            "Дніпропетровська область" to "Дніпропетровська область — Dnipropetrovsk oblast",
            "Житомирська область" to "Житомирська область — Zhytomyrs'ka oblast",
            "Закарпатська область" to "Закарпатська область — Zakarpats'ka oblast",
            "Запорізька область" to "Запорізька область — Zaporiz'ka oblast",
            "Івано-Франківська область" to "Івано-Франківська область — Ivano-Frankivs'ka oblast",
            "місто Київ" to "Київ — Kyiv city",
            "Київська область" to "Київська область — Kiev oblast",
            "Кіровоградська область" to "Кіровоградська область — Kirovohrads'ka oblast",
            "Львівська область" to "Львівська область — Lviv oblast",
            "Миколаївська область" to "Миколаївська область — Mykolaivs'ka oblast",
            "Одеська область" to "Одеська область — Odessa oblast",
            "Полтавська область" to "Полтавська область — Poltavs'ka oblast",
            "Рівненська область" to "Рівненська область — Rivnens'ka oblast",
            "Сумська область" to "Сумська область — Sums'ka oblast",
            "Тернопільська область" to "Тернопільська область — Ternopil's'ka oblast",
            "Харківська область" to "Харківська область — Kharkiv oblast",
            "Херсонська область" to "Херсонська область — Khersons'ka oblast",
            "Хмельницька область" to "Хмельницька область — Khmel'nyts'ka oblast",
            "Черкаська область" to "Черкаська область — Cherkas'ka oblast",
            "Чернівецька область" to "Чернівецька область — Chernivets'ka oblast",
            "Чернігівська область" to "Чернігівська область — Chernihivs'ka oblast",
        ),
        "US" to listOf(
            "AL" to "Alabama",
            "AK" to "Alaska",
            "AS" to "American Samoa",
            "AZ" to "Arizona",
            "AR" to "Arkansas",
            "AA" to "Armed Forces (AA)",
            "AE" to "Armed Forces (AE)",
            "AP" to "Armed Forces (AP)",
            "CA" to "California",
            "CO" to "Colorado",
            "CT" to "Connecticut",
            "DE" to "Delaware",
            "DC" to "District of Columbia",
            "FL" to "Florida",
            "GA" to "Georgia",
            "GU" to "Guam",
            "HI" to "Hawaii",
            "ID" to "Idaho",
            "IL" to "Illinois",
            "IN" to "Indiana",
            "IA" to "Iowa",
            "KS" to "Kansas",
            "KY" to "Kentucky",
            "LA" to "Louisiana",
            "ME" to "Maine",
            "MH" to "Marshall Islands",
            "MD" to "Maryland",
            "MA" to "Massachusetts",
            "MI" to "Michigan",
            "FM" to "Micronesia",
            "MN" to "Minnesota",
            "MS" to "Mississippi",
            "MO" to "Missouri",
            "MT" to "Montana",
            "NE" to "Nebraska",
            "NV" to "Nevada",
            "NH" to "New Hampshire",
            "NJ" to "New Jersey",
            "NM" to "New Mexico",
            "NY" to "New York",
            "NC" to "North Carolina",
            "ND" to "North Dakota",
            "MP" to "Northern Mariana Islands",
            "OH" to "Ohio",
            "OK" to "Oklahoma",
            "OR" to "Oregon",
            "PW" to "Palau",
            "PA" to "Pennsylvania",
            "PR" to "Puerto Rico",
            "RI" to "Rhode Island",
            "SC" to "South Carolina",
            "SD" to "South Dakota",
            "TN" to "Tennessee",
            "TX" to "Texas",
            "UT" to "Utah",
            "VT" to "Vermont",
            "VI" to "Virgin Islands",
            "VA" to "Virginia",
            "WA" to "Washington",
            "WV" to "West Virginia",
            "WI" to "Wisconsin",
            "WY" to "Wyoming",
        ),
        "UY" to listOf(
            "Artigas" to "Artigas",
            "Canelones" to "Canelones",
            "Cerro Largo" to "Cerro Largo",
            "Colonia" to "Colonia",
            "Durazno" to "Durazno",
            "Flores" to "Flores",
            "Florida" to "Florida",
            "Lavalleja" to "Lavalleja",
            "Maldonado" to "Maldonado",
            "Montevideo" to "Montevideo",
            "Paysandú" to "Paysandú",
            "Río Negro" to "Río Negro",
            "Rivera" to "Rivera",
            "Rocha" to "Rocha",
            "Salto" to "Salto",
            "San José" to "San José",
            "Soriano" to "Soriano",
            "Tacuarembó" to "Tacuarembó",
            "Treinta y Tres" to "Treinta y Tres",
        ),
        "UZ" to listOf(
            "Tashkent" to "Tashkent",
            "Andijan Region" to "Andijan Region",
            "Bukhara Region" to "Bukhara Region",
            "Fergana Region" to "Fergana Region",
            "Jizzakh Region" to "Jizzakh Region",
            "Namangan Region" to "Namangan Region",
            "Navoiy Region" to "Navoiy Region",
            "Qashqadaryo Region" to "Qashqadaryo Region",
            "Samarqand Region" to "Samarqand Region",
            "Sirdaryo Region" to "Sirdaryo Region",
            "Surxondaryo Region" to "Surxondaryo Region",
            "Tashkent Region" to "Tashkent Region",
            "Xorazm Region" to "Xorazm Region",
            "Karakalpakstan" to "Karakalpakstan",
        ),
        "VE" to listOf(
            "Amazonas" to "Amazonas",
            "Anzoátegui" to "Anzoátegui",
            "Apure" to "Apure",
            "Aragua" to "Aragua",
            "Barinas" to "Barinas",
            "Bolívar" to "Bolívar",
            "Carabobo" to "Carabobo",
            "Cojedes" to "Cojedes",
            "Delta Amacuro" to "Delta Amacuro",
            "Dependencias Federales" to "Dependencias Federales",
            "Distrito Federal" to "Distrito Federal",
            "Falcón" to "Falcón",
            "Guárico" to "Guárico",
            "Lara" to "Lara",
            "Mérida" to "Mérida",
            "Miranda" to "Miranda",
            "Monagas" to "Monagas",
            "Nueva Esparta" to "Nueva Esparta",
            "Portuguesa" to "Portuguesa",
            "Sucre" to "Sucre",
            "Táchira" to "Táchira",
            "Trujillo" to "Trujillo",
            "Vargas" to "Vargas",
            "Yaracuy" to "Yaracuy",
            "Zulia" to "Zulia",
        ),
        "VN" to listOf(
            "An Giang" to "An Giang — An Giang Province",
            "Bà Rịa–Vũng Tàu" to "Bà Rịa–Vũng Tàu — Ba Ria-Vung Tau Province",
            "Bạc Liêu" to "Bạc Liêu — Bac Lieu Province",
            "Bắc Giang" to "Bắc Giang — Bac Giang Province",
            "Bắc Kạn" to "Bắc Kạn — Bac Kan Province",
            "Bắc Ninh" to "Bắc Ninh — Bac Ninh Province",
            "Bến Tre" to "Bến Tre — Ben Tre Province",
            "Bình Dương" to "Bình Dương — Binh Duong Province",
            "Bình Định" to "Bình Định — Binh Dinh Province",
            "Bình Phước" to "Bình Phước — Binh Phuoc Province",
            "Bình Thuận" to "Bình Thuận — Binh Thuan Province",
            "Cà Mau" to "Cà Mau — Ca Mau Province",
            "Cao Bằng" to "Cao Bằng — Cao Bang Province",
            "Cần Thơ" to "Cần Thơ — Can Tho City",
            "Đà Nẵng" to "Đà Nẵng — Da Nang City",
            "Đắk Lắk" to "Đắk Lắk — Dak Lak Province",
            "Đăk Nông" to "Đăk Nông — Dak Nong Province",
            "Điện Biên" to "Điện Biên — Dien Bien Province",
            "Đồng Nai" to "Đồng Nai — Dong Nai Province",
            "Đồng Tháp" to "Đồng Tháp — Dong Thap Province",
            "Gia Lai" to "Gia Lai — Gia Lai Province",
            "Hà Giang" to "Hà Giang — Ha Giang Province",
            "Hà Nam" to "Hà Nam — Ha Nam Province",
            "Hà Nội" to "Hà Nội — Hanoi City",
            "Hà Tĩnh" to "Hà Tĩnh — Ha Tinh Province",
            "Hải Dương" to "Hải Dương — Hai Duong Province",
            "Hải Phòng" to "Hải Phòng — Haiphong City",
            "Hậu Giang" to "Hậu Giang — Hau Giang Province",
            "Hòa Bình" to "Hòa Bình — Hoa Binh Province",
            "Hưng Yên" to "Hưng Yên — Hung Yen Province",
            "Khánh Hòa" to "Khánh Hòa — Khanh Hoa Province",
            "Kiên Giang" to "Kiên Giang — Kien Giang Province",
            "Kon Tum" to "Kon Tum — Kon Tum Province",
            "Lai Châu" to "Lai Châu — Lai Chau Province",
            "Lạng Sơn" to "Lạng Sơn — Lang Song Province",
            "Lào Cai" to "Lào Cai — Lao Cai Province",
            "Lâm Đồng" to "Lâm Đồng — Lam Dong Province",
            "Long An" to "Long An — Long An Province",
            "Nam Định" to "Nam Định — Nam Dinh Province",
            "Nghệ An" to "Nghệ An — Nghe An Province",
            "Ninh Bình" to "Ninh Bình — Ninh Binh Province",
            "Ninh Thuận" to "Ninh Thuận — Ninh Thuan Province",
            "Phú Thọ" to "Phú Thọ — Phu Tho Province",
            "Phú Yên" to "Phú Yên — Phu Yen Province",
            "Quảng Bình" to "Quảng Bình — Quang Binh Province",
            "Quảng Nam" to "Quảng Nam — Quang Nam Province",
            "Quảng Ngãi" to "Quảng Ngãi — Quang Ngai Province",
            "Quảng Ninh" to "Quảng Ninh — Quang Ninh Province",
            "Quảng Trị" to "Quảng Trị — Quang Tri Province",
            "Sóc Trăng" to "Sóc Trăng — Soc Trang Province",
            "Sơn La" to "Sơn La — Son La Province",
            "Tây Ninh" to "Tây Ninh — Tay Ninh Province",
            "Thái Bình" to "Thái Bình — Thai Binh Province",
            "Thái Nguyên" to "Thái Nguyên — Thai Nguyen Province",
            "Thanh Hóa" to "Thanh Hóa — Thanh Hoa Province",
            "Thành phố Hồ Chí Minh" to "Thành phố Hồ Chí Minh — Ho Chi Minh City",
            "Thừa Thiên–Huế" to "Thừa Thiên–Huế — Thua Thien-Hue Province",
            "Tiền Giang" to "Tiền Giang — Tien Giang Province",
            "Trà Vinh" to "Trà Vinh — Tra Vinh Province",
            "Tuyên Quang" to "Tuyên Quang — Tuyen Quang Province",
            "Vĩnh Long" to "Vĩnh Long — Vinh Long Province",
            "Vĩnh Phúc" to "Vĩnh Phúc — Vinh Phuc Province",
            "Yên Bái" to "Yên Bái — Yen Bai Province",
        ),
    )

    /** Whether the given country shows a state field at all. */
    fun hasState(countryCode: String): Boolean {
        val code = countryCode.uppercase()
        return STATE_LISTS.containsKey(code) || STATE_FREETEXT_COUNTRIES.contains(code)
    }

    /** State dropdown options for the given country, or null when there is no fixed list. */
    fun stateList(countryCode: String): List<Pair<String, String>>? =
        STATE_LISTS[countryCode.uppercase()]

    /**
     * Normalize a free-text state to its canonical dropdown value.
     *
     * Matches case-insensitively against either the option value or label.
     * Returns the input unchanged when no list exists
     * or no match is found, so callers can pass through arbitrary user input.
     */
    fun mapState(countryCode: String, stateInput: String): String {
        if (stateInput.isBlank()) return stateInput
        val list = stateList(countryCode) ?: return stateInput
        val trimmed = stateInput.trim()
        val match = list.firstOrNull { (value, label) ->
            value.equals(trimmed, ignoreCase = true) || label.equals(trimmed, ignoreCase = true)
        }
        return match?.first ?: stateInput
    }
}
