package com.airwallex.android.core

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class GooglePayOptions(
    /**
     * The Google Pay API may return cards on file on Google.com (PAN_ONLY) and/or a device token on
     * an Android device authenticated with a 3-D Secure cryptogram (CRYPTOGRAM_3DS). Default: Both
     * authentication methods are allowed.
     */
    val allowedCardAuthMethods: List<String>? = null,
    /**
     * Merchant name encoded as UTF-8.
     */
    val merchantName: String? = null,
    /**
     * Set to false if you don't support prepaid cards. Default: The prepaid card class is supported
     * for the card networks specified.
     */
    val allowPrepaidCards: Boolean? = null,
    /**
     * Set to false if you don't support credit cards. Default: The credit card class is supported
     * for the card networks specified.
     */
    val allowCreditCards: Boolean? = null,
    /**
     * Set to true to request assuranceDetails. This object provides information about the
     * validation performed on the returned payment data.
     */
    val assuranceDetailsRequired: Boolean? = null,
    /**
     * Set to true if you require a billing address. A billing address should only be requested if
     * it's required to process the transaction.
     */
    val billingAddressRequired: Boolean? = null,
    /**
     * The expected fields returned if billingAddressRequired is set to true.
     */
    val billingAddressParameters: BillingAddressParameters? = null,
    /**
     * Correlation ID to refer to this transaction.
     *
     * This field is optional. It is generated by the merchant and is used
     * for referring to this transaction later on (e.g. for debugging issues
     * when communicating with Google).
     */
    val transactionId: String? = null,
    /**
     * Provide a business name for the label field. Use the same business name people will see when
     * they look for the charge on their bank or credit card statement. For example, "COMPANY, INC."
     */
    val totalPriceLabel: String? = null,
    /**
     * Affects the submit button text displayed in the Google Pay payment sheet.
     * DEFAULT: Standard text applies for the given totalPriceStatus (default).
     * COMPLETE_IMMEDIATE_PURCHASE: The selected payment method is charged immediately after the payer
     * confirms their selections.
     */
    val checkoutOption: String? = null,
    /**
     * Set to true to request an email address.
     */
    val emailRequired: Boolean? = null,
    /**
     * Set to true to request a full shipping address.
     * Note: The shipping address is currently provided and saved when merchant creating a payment intent,
     * so this won't be useful until we support confirming a payment intent with shipping address.
     */
    val shippingAddressRequired: Boolean? = null,
    /**
     * If shippingAddressParameters is set to true, specify shipping address restrictions.
     */
    val shippingAddressParameters: ShippingAddressParameters? = null,

    /**
     * The card networks that your application accepts
     * @see [allowedCardNetworks](https://developers.google.com/pay/api/android/reference/request-objects#CardParameters)
     * So far, we have supported the following types: AMEX, DISCOVER, JCB, MASTERCARD, VISA, MAESTRO.
     * If you do not set this list, we will default to supporting these types: AMEX, DISCOVER, JCB, MASTERCARD, VISA.
     * If you want to support MAESTRO, set the value for allowedCardNetworks. Note that if you add MAESTRO, your countryCode must include BR.
     * If you include types that we do not support, the payment process will fail.
     */
    val allowedCardNetworks: List<String> = googlePaySupportedNetworks(),

    /**
     * Setting skipReadinessCheck to true will skip the IsReadyToPay check before invoking Google Pay.
     * @see [IsReadyToPay](https://developers.google.com/pay/api/android/reference/client#isReadyToPay)
     * On certain models from brands like Xiaomi and Honor, IsReadyToPay always returns false, which can block Google Pay.
     * Skipping this check will try to launch Google Pay sheet directly.
     * We advise you to carefully consider whether to skip this step.
     */
    val skipReadinessCheck: Boolean? = false
) : Parcelable

@Parcelize
data class BillingAddressParameters(
    val format: Format? = Format.MIN,
    val phoneNumberRequired: Boolean? = false
) : Parcelable {
    enum class Format {
        MIN,
        FULL
    }
}

@Parcelize
data class ShippingAddressParameters(
    val allowedCountryCodes: List<String>? = null,
    val phoneNumberRequired: Boolean? = false
) : Parcelable