name: Push release to Maven

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  maven:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout project
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # 3.6.0

      - name: Set up our JDK environment
        uses: actions/setup-java@17f84c3641ba7b8f6deff6309fc4c864478f5d62 #3.14.1
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Packages and publishes to Maven Central
      - name: Publish to Maven Central
        run: |
          ./gradlew --stacktrace \
          publishReleasePublicationToSonatypeRepository --max-workers 1 \
          closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          AIRWALLEX_VERSION_CODE: ${{ github.run_number }}
