name: Push release to Maven

on:
  workflow_dispatch:
  push:
    tags:
      - '*'

jobs:
  maven:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up our JDK environment
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle check
        run: ./gradlew check

      # Packages and publishes to Maven Central
      - name: Publish to Maven Central
        run: |
          ./gradlew --stacktrace \
          publishReleasePublicationToSonatypeRepository --max-workers 1 \
          closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_BASE64: ${{ secrets.SIGNING_KEY_BASE64 }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
          AIRWALLEX_VERSION_CODE: ${{ github.run_number }}