name: Repo Dispatch on Android Release

on:
  workflow_call:
    inputs:
      tag:
        description: 'Android SDK version (e.g., 6.3.0)'
        required: true
        type: string
  workflow_dispatch:
    inputs:
      tag:
        description: 'Android SDK version (e.g., 6.3.0)'
        required: true
        type: string

jobs:
  repo-dispatch-on-release:
    runs-on: ubuntu-latest
    steps:
      - name: Log version
        run: 'echo "Dispatching for version: ${{ inputs.tag }}"'
      - name: Send repository dispatch to Flutter SDK
        env:
          GH_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        run: |
          gh api repos/airwallex/airwallex-payment-flutter/dispatches \
            --method POST \
            --field event_type='android_release' \
            --field client_payload[tag]='${{ inputs.tag }}'

      - name: Send repository dispatch to React Native SDK
        env:
          GH_TOKEN: ${{ secrets.SERVICE_ACCOUNT_PAT }}
        run: |
          gh api repos/airwallex/airwallex-payment-react-native/dispatches \
            --method POST \
            --field event_type='android_release' \
            --field client_payload[tag]='${{ inputs.tag }}'
