name: Run Tests
on:
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize ]
  push:
    branches: [ develop, main ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop for Sonar
        uses: actions/checkout@v2
        with:
          ref: develop

      - name: Checkout the code
        uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up our JDK environment
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Run tests with coverage
        run: ./gradlew jacocoTestDebugUnitTestReport
      
      - name: SonarQube with Pull Request Decoration
        if: github.event.number != null
        run: ./gradlew sonarqube -Dsonar.qualitygate.wait=true -Dsonar.pullrequest.key=${{ github.event.number }} -Dsonar.pullrequest.branch=${{ github.ref }} -Dsonar.pullrequest.base=${{ github.base_ref }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
      - name: SonarQube without Pull Request Decoration
        if: github.event.number == null
        run: ./gradlew sonarqube -Dsonar.qualitygate.wait=true
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v1.6
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          files: "**/build/test-results/**/*.xml"

